### ISSUE TITLE
Move project to WebdriverIO Community Org

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio-community/wdio-safaridriver-service#3]
Hey @aruiz-caritsqa,

first off, thank you for creating this plugin and extending the WebdriverIO ecosystem!

I was wondering if you would be interested moving this repository into the [WebdriverIO Community](https://github.com/webdriverio-community) organisation. It would allow us to help maintain this package, automate a few things like releases and allow others to contribute to it and make the package even better. You would of course continue to have full access to it.

What do you think? Please let me know if you have any questions.

**Comment by aruiz-caritsqa** [comment]
Hi Christian,

I'm very happy to transfer this to webdriverio-community.

I just tried to do it, but I don't have permission to create repos there.

Cheers,

Adrien

**Comment by christian-bromann** [comment]
@aruiz-caritsqa I just invited you to the org. Please also make [`~wdio-user`](https://www.npmjs.com/~wdio-user) an NPM package maintainer so we can automate releases. Thank you!

**Comment by christian-bromann** [comment]
@aruiz-caritsqa any updates? We would really help to maintain the project but can't until it is part of the community organisation.

**Comment by christian-bromann** [comment]
Closing as this was successfully transferred to the community organisation. Thank you @aruiz-caritsqa !
