### ISSUE TITLE
Safari WebExtension

### ISSUE THREAD

**Issue by jRichardeau** [webdriverio-community/wdio-safaridriver-service#4]
Hello,

Is there a way to load a safari web extension with this driver ?

Thank you

**Comment by jRichardeau** [comment]
Hi ! Anyone there ?

**Comment by christian-bromann** [comment]
Yup - I saw your issue but don't have an answer for it.

**Comment by christian-bromann** [comment]
As far as I am aware Safari doesn't allow loading Web Extensions through Safaridriver.

**Comment by christian-bromann** [comment]
If anyone has a clue how this can be implemented, that would be awesome.

**Comment by christian-bromann** [comment]
See more about this https://github.com/webdriverio/webdriverio/issues/10347 .. is short: WebDriver Bidi will likely include support for cross browser support of web extensions.
