### ISSUE TITLE
navigator.webdriver false in Safari iOS

### ISSUE THREAD

**Issue by kopax-polyconseil** [webdriverio-community/wdio-safaridriver-service#72]
Tested on iPhone 13 iOS 15.2 among many platform, this is the only one where `navigator.webdriver = false`

I expect it to be `true`.

**Comment by christian-bromann** [comment]
As mentioned in our Gitter channel, this is a Safaridriver issue and can't be fixed as part of this service. Please file an issue in the Safaridriver project (not sure of Apple still exposes that project page).
